spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        ### USER ###
        ### <REGISTER> : PERMIT ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        ### <USER-CHECK> : PERMIT ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/welcome, /user-service/health_check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        ### <Login, Reissue> : PERMIT ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/tokens/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        ### <USER-SERVICE> : AUTHORIZATION ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/users/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ### <ACTUATOR> ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"