server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: api-gateway-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: msa_user
#    password: test123
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        ### USER ###
        ### <REGISTER> : PERMIT ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        ### <USER-CHECK> : PERMIT ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/welcome, /user-service/health_check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        ### <Login, Reissue> : PERMIT ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/tokens/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        ### <USER-SERVICE> : AUTHORIZATION ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/api/users/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ### <ACTUATOR> ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  expiration_time: 86400000
  secret: cf0ac9608f0325faf5e8085deb19c8f6e90140354135b0c509988c36b0a2fa11